import { all_routes } from "../../feature-module/router/all_routes";
const routes = all_routes;


  export const  header = [
      {
        title: 'Home',
        showAsTab: false,
        separateRoute: true,
        hasSubRoute: false,
        showSubRoute: false,
        routes: routes.home,
        base: 'home'
      },
      {
        title: 'Listing',
        showAsTab: false,
        separateRoute: false,
        base: 'listing',
        menu: [
          {
            menuValue: 'Buy Property',
            hasSubRoute: true,
            showSubRoute: false,
            page: 'buy-property',
            subMenus: [
              {
                menuValue: 'Buy Grid',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                links:[],
                routes: routes.buyPropertyGrid,
              },
              {
                menuValue: 'Buy List',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.buyPropertyList,
              },
              {
                menuValue: 'Buy Grid With Sidebar',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.buyPropertyGridSidebar,
              },
              {
                menuValue: 'Buy List With Sidebar',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.buyPropertyListSidebar,
              },
              // {
              //   menuValue: 'Buy Grid with map',
              //   hasSubRoute: false,
              //   showSubRoute: false,
              //   subMenus: [],
              //   routes: routes.buyGridWithMap,
              // },
              // {
              //   menuValue: 'Buy List with map',
              //   hasSubRoute: false,
              //   showSubRoute: false,
              //   subMenus: [],
              //   routes: routes.buyListWithMap,
              // },
              {
                menuValue: 'Buy Details',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.buyDetails,
              },
            ],
          },
          {
            menuValue: 'Rent Property',
            hasSubRoute: true,
            showSubRoute: false,
            openInNewTab: false,
            // page: 'doctor-dashboard',
            routes: routes.rentGrid,
            subMenus: [
              {
                menuValue: 'Rent Grid',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.rentGrid,
              },
              {
                menuValue: 'Rent List',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.rentPropertyList,
              },
              {
                menuValue: 'Rent Grid With Sidebar',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.rentGridWithSidebar,
              },
              {
                menuValue: 'Rent List With Sidebar',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.rentPropertyListSidebar,
              },
              // {
              //   menuValue: 'Rent Grid with map',
              //   hasSubRoute: false,
              //   showSubRoute: false,
              //   subMenus: [],
              //   routes: routes.rentGridMap,
              // },
              // {
              //   menuValue: 'Rent List with map',
              //   hasSubRoute: false,
              //   showSubRoute: false,
              //   subMenus: [],
              //   routes: routes.rentListMap,
              // },
              {
                menuValue: 'Rent Details',
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
                routes: routes.rentDetails,
              },
            ],
          },
        ],
      },
      {
        title: 'Agent',
        showAsTab: false,
        separateRoute: false,
        base: 'agent',
        menu: [
          {
            menuValue: 'Agent Grid',
            routes: routes.agentGrid,
            hasSubRoute: false,
            showSubRoute: false,
            page: "agent-grid",
            subMenus: [],
          },
          {
            menuValue: 'Agent List',
            page: "agent-list",
            routes: routes.agentList,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agent Grid With Sidebar',
            page: "agent-grid-sidebar",
            routes: routes.agentGridSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agent List With Sidebar',
            page: "agent-list-sidebar",
            routes: routes.agentListSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agent Details',
            page: "agent-details",
            routes: routes.agentDetails,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        title: 'Agency',
        showAsTab: false,
        separateRoute: false,
        base: 'agency',
        menu: [
          {
            menuValue: 'Agency Grid',
            routes: routes.agencyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            page: "agency-grid",
            subMenus: [],
          },
          {
            menuValue: 'Agency List',
            routes: routes.agencyList,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agency Grid With Sidebar',
            routes: routes.agencyGridSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agency List With Sidebar',
            routes: routes.agencyListSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Agency Details',
            routes: routes.agencyDetails,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        title: 'Pages',
        showAsTab: false,
        separateRoute: false,
        base: 'pages',
        menu: [
          {
            menuValue: 'About Us',
            routes: routes.aboutUs,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Authentication',
            hasSubRoute: true,
            showSubRoute: false,
            subMenus: [
              {
                menuValue: 'Signup',
                routes: routes.register,
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
              {
                menuValue: 'Signin',
                routes: routes.login,
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
              {
                menuValue: 'Forgot Password',
                routes: routes.forgotPassword,
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
              {
                menuValue: 'Reset Password',
                routes: routes.restPassword,
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
            ],
          },
          {
            menuValue: 'Invoice Details',
            hasSubRoute: false,
            showSubRoute: false,
            routes: routes.InvoiceDetails,

          },
          {
            menuValue: 'Error Page',
            hasSubRoute: true,
            showSubRoute: false,
            subMenus: [
              {
                menuValue: '404 Error',
                routes: routes.error404,

                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
              {
                menuValue: '500 Error',
                routes: routes.error500,
                hasSubRoute: false,
                showSubRoute: false,
                subMenus: [],
              },
            ],
          },
          {
            menuValue: 'Pricing',
            routes: routes.pricingplan,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'FAQ',
            routes: routes.faq,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Gallery',
            routes: routes.gallery,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Our Team',
            routes: routes.ourTeam,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Testimonials',
            routes: routes.testimonial,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Terms & Conditions',
            routes: routes.termsCondition,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Privacy Policy',
            routes: routes.privacyPolicy,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Maintenance',
            routes: routes.Maintenace,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Coming Soon',
            routes: routes.comingSoon,

            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        title: 'Blog',
        showAsTab: false,
        separateRoute: false,
        base: 'blog',
        menu: [
          {
            menuValue: 'Blog List',
            routes: routes.blogList,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Blog Grid',
            routes: routes.blogGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: 'Blog Details',
            routes: routes.blogDetails,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        title: 'Contact Us',
        showAsTab: false,
        base: 'contact-us',
        separateRoute: true,
        routes: routes.ContactUs,
        hasSubRoute: false,
        showSubRoute: false,
      },
    ];
  